### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security sigue la Directiva de ciclo de vida fijo.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908920"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security sigue la Directiva de ciclo de vida [fijo](/lifecycle/policies/fixed) .


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Vínculos \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront Client Security se ha discontinuado. El soporte técnico va a finalizar el 14 de julio de 2015. Las actualizaciones de definiciones antimalware y antispyware ya no estarán disponibles después de la finalización del soporte técnico para la versión del producto. Evalúe System Center Endpoint Protection como un reemplazo."
