### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security se rige por la directiva de ciclo de vida fijo.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security se rige por la directiva de ciclo de vida [fijo](/lifecycle/policies/fixed).


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Vínculos 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security se descontinuó el 14 de julio de 2015. Las actualizaciones de definiciones antimalware y antispyware ya no estarán disponibles después del fin de soporte de la versión del producto. Considere System Center Endpoint Protection como posible reemplazo.