### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Microsoft Application Virtualization 4.6 se rige por la Directiva de ciclo de vida fijo.
  ms.date: 09/01/2020
  keywords: 'for Remote Desktop Services,for Windows Desktops,Sequencer'
name: Microsoft Application Virtualization 4.6
summary: |+
  Microsoft Application Virtualization 4.6 se rige por la Directiva de ciclo de vida [fijo](/lifecycle/policies/fixed).

  Esto se aplica a las siguientes ediciones: for Remote Desktop Services, para Windows Desktops y Sequencer

products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>Vínculos 
  * [Información sobre el producto y la migración](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Instrucciones para la migración](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)
  * [Directiva del Service Pack](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > Dado que el cliente de App-V 4.6 utiliza el servidor de App-V 4.5, este último seguirá recibiendo soporte técnico según las fechas del ciclo de vida de App-V 4.6 cuando se use con el cliente de App-V 4.6 compatible.

  ## <a name="editions"></a>Ediciones 
  * for Remote Desktop Services
  * para escritorios de Windows
  * Sequencer