### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
  description: Microsoft Application Virtualization Hosting 5.1 para escritorios de Windows se rige por la directiva de ciclo de vida fijo.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 9296a136a0bc0da5a6d6b6b8b49d012170158da0
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1000593"
name: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
summary: >+
  Microsoft Application Virtualization Hosting 5.1 para escritorios de Windows se rige por la directiva de ciclo de vida [fijo](/lifecycle/policies/fixed).


  Esto está disponible para las siguientes ediciones: para escritorio de Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Vínculos \n* [Información del producto](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Ediciones \n* para escritorios de Windows"
