### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 Configuration Manager
  description: Microsoft System Center 2012 Configuration Manager se rige por la Directiva de ciclo de vida fijo.
  ms.date: 03/12/2021
  keywords: null
name: Microsoft System Center 2012 Configuration Manager
summary: |+
  Microsoft System Center 2012 Configuration Manager se rige por la Directiva de ciclo de vida [fijo](/lifecycle/policies/fixed).


products:
  - msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
  - version: Service Pack 2
    startDate: 05/12/2015
    endDate: 07/12/2022
  - version: Service Pack 1
    startDate: 12/15/2012
    endDate: 07/12/2016
  - version: Original Release
    startDate: 05/30/2012
    endDate: 01/14/2014
content: |+

  ## <a name="links"></a>Vínculos 
  * [Directiva del Service Pack](/lifecycle/policies/fixed#service-packs)
  * [Documentación de System Center](/system-center/#pivot=components&panel=components-all)
  * [Recursos de System Center](https://www.microsoft.com/system-center/resources)
  * [Instrucciones para la migración](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)