### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
  description: Microsoft Application Virtualization Hosting 5.1 para escritorios de Windows se rige por la directiva de ciclo de vida fijo.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: eb73a1103424c9b0900a18fc09bb6bc0685b646d
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4114314"
name: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
summary: >+
  Microsoft Application Virtualization Hosting 5.1 para escritorios de Windows se rige por la directiva de ciclo de vida [fijo](/lifecycle/policies/fixed).


  Esto está disponible para las siguientes ediciones: para escritorio de Windows

products:
- windows
policyType: fixed
supportDates:
  start: 2015-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2026-04-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2015-11-01T00:00:00.000-08:00
  endDate: 2026-04-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Vínculos \n* [Información del producto](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Ediciones \n* para escritorios de Windows"
