### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
  description: Microsoft Application Virtualization Hosting 5.1 para escritorios de Windows se rige por la directiva de ciclo de vida fijo.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "863664"
name: Microsoft Application Virtualization Hosting 5.1 for Windows Desktops
summary: >+
  Microsoft Application Virtualization Hosting 5.1 para escritorios de Windows se rige por la directiva de ciclo de vida [fijo](/lifecycle/policies/fixed).


  Esto está disponible para las siguientes ediciones: para escritorio de Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Vínculos \n* [Información del producto](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Ediciones \n* para escritorios de Windows"
