### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 se rige por la Directiva de ciclo de vida fijo.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 se rige por la Directiva de ciclo de vida [fijo](/lifecycle/policies/fixed).


  > [!IMPORTANT]
  > El soporte técnico para este producto ha finalizado. Consulte las instrucciones de migración a continuación.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Vínculos 
  * [Instrucciones para la migración](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Instrucciones de migración adicionales](/mem/configmgr/core/migration/planning-for-migration)