### YamlMime:Lifecycle
metadata:
  title: Hospedaje de Microsoft Application Virtualization 5,1 para escritorios de Windows
  description: Microsoft Application Virtualization Hosting 5,1 para escritorios de Windows sigue la Directiva de ciclo de vida fijo.
  ms.date: 07/28/2020
  ms.openlocfilehash: c6fc257da84e3276165d0ab97a736120c1424172
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "863664"
name: Hospedaje de Microsoft Application Virtualization 5,1 para escritorios de Windows
summary: >+
  Microsoft Application Virtualization Hosting 5,1 para escritorios de Windows sigue la Directiva de ciclo de vida [fijo](/lifecycle/policies/fixed) .


  Esto se aplica a las siguientes ediciones: para escritorios de Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Vínculos \n* [Información del producto](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Ediciones \n* para escritorios de Windows"
