### YamlMime:Lifecycle
metadata:
  title: Conjunto de aplicaciones de PixelSense 1,0
  description: PixelSense Application Suite 1,0 sigue la Directiva de ciclo de vida fijo.
  ms.date: 07/28/2020
  ms.openlocfilehash: 5359b0dd917124f3b47cb74f30a3ff92657c2155
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "840725"
name: Conjunto de aplicaciones de PixelSense 1,0
summary: >+
  PixelSense Application Suite 1,0 sigue la Directiva de ciclo de vida [fijo](/lifecycle/policies/fixed) .


products:
- windows
policyType: fixed
supportDates:
  start: 01/01/2009
  end: 01/14/2014
  extendedEnd: 01/08/2019
releases:
- version: Service Pack 1
  startDate: 08/09/2009
  endDate: 01/08/2019
- version: Original Release
  startDate: 01/01/2009
  endDate: 01/14/2014
content: ''
