### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: SoftGrid Application Virtualization se rige por la directiva de ciclo de vida fijo.
  ms.date: 07/28/2020
  ms.openlocfilehash: 17b8078138b718a634c2561ac4b1e73f3966ce24
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: es-ES
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "840190"
name: SoftGrid Application Virtualization
summary: >
  SoftGrid Application Virtualization se rige por la directiva de ciclo de vida [fijo](/lifecycle/policies/fixed).


  Esto está disponible para las siguientes ediciones: 4.1 para Desktops, 4.2 para Desktops y para Terminal Services 4.1


  > [!IMPORTANT]

  > El soporte técnico ha finalizado. Consulte las instrucciones de migración a continuación.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Vínculos \n* [Instrucciones para la migración](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Ediciones \n* 4.1 para Desktops\n* 4.2 para Desktops\n* para Terminal Services 4.1"
