### YamlMime:Lifecycle
metadata:
  title: Puerta de enlace de aplicaciones inteligentes de comunicaciones de Whale
  description: La puerta de enlace de aplicaciones inteligente de comunicaciones de Whale sigue la Directiva de ciclo de vida fijo.
  ms.date: 08/21/2020
  ms.openlocfilehash: 4946cfbd0c53706853138bd707157a5c318b8dc6
  ms.sourcegitcommit: bc7fcda30191f92db77ed2e7f74d5816ac276a55
  ms.translationtype: MT
  ms.contentlocale: es-ES
  ms.lasthandoff: 08/21/2020
  ms.locfileid: "907158"
name: Puerta de enlace de aplicaciones inteligentes de comunicaciones de Whale
summary: >+
  La puerta de enlace de aplicaciones inteligente de comunicaciones de Whale sigue la Directiva de ciclo de vida [fijo](/lifecycle/policies/fixed) .


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 10/10/2007
  end: 07/13/2010
releases:
- version: "3.1"
  startDate: 10/10/2007
  endDate: 07/08/2008
- version: "3.6"
  startDate: 10/10/2007
  endDate: 07/13/2010
content: "\n\n> [!NOTE]\n> El soporte técnico para este producto está sujeto a los términos de su adquisición."
